// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Lm-ZUNcTF7M6I_IPwpDeewjR9SzHWOk',
    appId: '1:950472488661:web:3184808555bed839fb145c',
    messagingSenderId: '950472488661',
    projectId: 'my-garden-4a739',
    authDomain: 'my-garden-4a739.firebaseapp.com',
    storageBucket: 'my-garden-4a739.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkAtF93CiI-YDXv3zxoTrKz8bjbxBDcEA',
    appId: '1:950472488661:android:c1e9081850bc14c1fb145c',
    messagingSenderId: '950472488661',
    projectId: 'my-garden-4a739',
    storageBucket: 'my-garden-4a739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcA4uQ0dhmpW75W6xqJuymXSb8FaJK9GM',
    appId: '1:950472488661:ios:805e9165e5a1b47bfb145c',
    messagingSenderId: '950472488661',
    projectId: 'my-garden-4a739',
    storageBucket: 'my-garden-4a739.firebasestorage.app',
    iosBundleId: 'com.example.myGardenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcA4uQ0dhmpW75W6xqJuymXSb8FaJK9GM',
    appId: '1:950472488661:ios:805e9165e5a1b47bfb145c',
    messagingSenderId: '950472488661',
    projectId: 'my-garden-4a739',
    storageBucket: 'my-garden-4a739.firebasestorage.app',
    iosBundleId: 'com.example.myGardenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Lm-ZUNcTF7M6I_IPwpDeewjR9SzHWOk',
    appId: '1:950472488661:web:86359f3d6ec97f14fb145c',
    messagingSenderId: '950472488661',
    projectId: 'my-garden-4a739',
    authDomain: 'my-garden-4a739.firebaseapp.com',
    storageBucket: 'my-garden-4a739.firebasestorage.app',
  );
}
